version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: db.dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tag_embeddings
    ports:
      - "5432:5432"

volumes:
  pgvector_data:
