version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: dockerfiles/db.dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tag_embeddings
    ports:
      - "5432:5432"
  ollama:
    build:
      context: .
      dockerfile: dockerfiles/ollama.dockerfile
    entrypoint: ["ollama", "serve"]
    ports:
      - "11434:11434"

volumes:
  pgvector_data:
