version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: db.dockerfile
    environment:
      - POSTGRES_USER=${DB_USER}:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS}:-postgres}
      - POSTGRES_DB=${DB_NAME}:-tag_embeddings}
    ports:
      - "5432:5432"

volumes:
  pgvector_data:
