"""tag_embedding_table

Revision ID: 88f7d4fd93d6
Revises: 372ffb57a810
Create Date: 2025-03-14 00:10:10.291706

"""

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "88f7d4fd93d6"
down_revision: Union[str, None] = "372ffb57a810"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag_embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=False),
        sa.Column("attribution", sa.String(), nullable=True),
        sa.Column("image_embeddings", Vector(dim=768), nullable=False),
        sa.Column("insert_timestamp", sa.DateTime(), nullable=False),
        sa.Column(
            "coordinates",
            geoalchemy2.types.Geometry(
                geometry_type="POINT", from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        "tag_embeddings_hnsw_cosine_similarity_idx",
        "tag_embeddings",
        ["image_embeddings"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"image_embeddings": "vector_cosine_ops"},
    )

    # op.create_index(
    #     "idx_tag_embeddings_coordinates",
    #     "tag_embeddings",
    #     ["coordinates"],
    #     unique=False,
    #     postgresql_using="gist",
    # )

    op.create_unique_constraint(None, "tag_embeddings", ["image_url"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tag_embeddings", type_="unique")
    # op.drop_index(
    #     "idx_tag_embeddings_coordinates",
    #     table_name="tag_embeddings",
    #     postgresql_using="gist",
    # )
    op.drop_index(
        "tag_embeddings_hnsw_cosine_similarity_idx",
        table_name="tag_embeddings",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"image_embeddings": "vector_cosine_ops"},
    )
    op.drop_table("tag_embeddings")
    # ### end Alembic commands ###
