name: Build

on:
  # push:
  #   branches:
  #     - main
  workflow_call:
    outputs:
      app_image_tag:
        description: "App image tag"
        value: ${{ jobs.build-osm-tagger.outputs.image_tag }}
      app_image_name:
        description: "App image name"
        value: ${{ jobs.build-osm-tagger.outputs.image_name }}
      ollama_image_tag:
        description: "Ollama image tag"
        value: ${{ jobs.build-ollama.outputs.image_tag }}
      ollama_image_name:
        description: "Ollama image name"
        value: ${{ jobs.build-ollama.outputs.image_name }}

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build-osm-tagger:
    runs-on: ubuntu-latest
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
      - name: Build and push image
        uses: hotosm/gh-workflows/.github/workflows/image_build.yml@3.1.1
        with:
          image_name: ghcr.io/${{ github.repository }}/osm-tagger
          dockerfile: dockerfiles/app.dockerfile
          multi_arch: true
    # outputs:
    #   image_name: ${{ jobs.build-image.outputs.image_name }}
    #   image_tag: ${{ jobs.build-image.outputs.image_tag }}

  build-ollama:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@3.1.1
    with:
      image_name: ghcr.io/${{ github.repository }}/osm-tagger-ollama
      dockerfile: dockerfiles/ollama.dockerfile
      multi_arch: true
    # outputs:
    #   image_name: ${{ jobs.build-image.outputs.image_name }}
    #   image_tag: ${{ jobs.build-image.outputs.image_tag }}
