name: Build

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build-osm-tagger:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@3.1.1
    with:
      image_name: ghcr.io/${{ github.repository }}/osm-tagger
      dockerfile: dockerfiles/app.dockerfile
      multi_arch: true
    outputs:
      image_name: ${{ jobs.build-image.outputs.image_name }}
      image_tag: ${{ jobs.build-image.outputs.image_tag }}

  build-ollama:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@3.1.1
    with:
      image_name: ghcr.io/${{ github.repository }}/osm-tagger-ollama
      dockerfile: dockerfiles/ollama.dockerfile
      multi_arch: true
    outputs:
      image_name: ${{ jobs.build-image.outputs.image_name }}
      image_tag: ${{ jobs.build-image.outputs.image_tag }}
