name: Deploy Pipeline

on:
  push:
    branches:
      # - main
      - initial-deployment
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

  build-osm-tagger:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@3.1.1
    needs: cleanup
    with:
      image_name: ghcr.io/${{ github.repository }}/osm-tagger
      dockerfile: dockerfiles/app.dockerfile

  deploy-infra:
    needs: build-osm-tagger
    uses: ./.github/workflows/infra.yaml
    with:
      app_image_tag: ${{ needs.build-osm-tagger.outputs.image_tag }}
      ollama_image_tag: main
    secrets:
      AWS_OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}
